# .repo.toml

# TODO: mirrors later

[about]
description = "GitHub CLI extension for PR approval/merge/pull workflow"
topics = ["gh-extension", "github-cli", "pull-requests", "workflow"]
license = "GPL-2.0-only"

[urls]
git_ssh = "git@github.com:fini-net/gh-amp.git"
web_url = "https://github.com/fini-net/gh-amp"

[flags]
claude = true
claude-review = true
copilot-review = true
standard-release = true
